unstable_features = true

# comments
comment_width = 100
wrap_comments = true

# imports
imports_granularity = "Crate"
reorder_imports = true

# strings
format_strings = false

max_width = 100

match_block_trailing_comma = true
