name: p2p-network-tests
on:
  push:
    branches: ["**"]
jobs:
  p2p-network-tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: |
            ~/cache/yarn
            ~/cache/cypress
          # Reuses cache from `build` workflow
          key: build-${{ runner.os }}-yarn-v5-${{ hashFiles('yarn.lock') }}
      - name: Cache Rust
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git
            ./target/*/deps
            ./target/*/build
            ./target/*/.fingerprint
          key: build-${{ runner.os }}-rust-v6-${{ hashFiles('Cargo.lock') }}
      - run: ci/p2p-network-tests.sh
