name: p2p-network-tests
on:
  push:
    branches: ["**"]
jobs:
  p2p-network-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: |
            ~/cache/yarn
            ~/cache/cypress
          key: build-${{ runner.os }}-yarn-v4-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            build-${{ runner.os }}-yarn-v4-
      - name: Cache Rust
        uses: actions/cache@v2
        with:
          path: |
            /usr/local/bin/cargo-deny
            ~/.cargo/advisory-db/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git
            ./target/*/deps
            ./target/*/build
            ./target/*/.fingerprint
          key: build-${{ runner.os }}-rust-v4-${{ hashFiles('Cargo.lock') }}
      - run: ci/p2p-network-tests.sh
